### ISSUE TITLE
Can you share the coo_feature matrix?

### ISSUE THREAD

**Issue by xs14331309** [vered1986/UnsupervisedHypernymy#4]
I want to compare my method with baseline in your paper, but i can't get the sampe feature weighting matrix.

**Comment by vered1986** [comment]
Co-occurrence matrix of which DSM?

**Comment by xs14331309** [comment]
> Co-occurrence matrix of which DSM?

yes! plz!

**Comment by vered1986** [comment]
Sorry, I meant I need you to specify which DSM you need, which is a combination of the following:

**Context Type** - window 2/5 / dependency-based / joint dependencies
**Feature Weighting** - none (frequency) / PPMI / PLMI

Each of these is a very large file which is not easy for me to transfer (they are on a server in my previous university), so if you only need one of them, I'll send it, otherwise I think it's best that you use our code to reconstruct them.

**Comment by xs14331309** [comment]
> Sorry, I meant I need you to specify which DSM you need, which is a combination of the following:
> 
> **Context Type** - window 2/5 / dependency-based / joint dependencies
> **Feature Weighting** - none (frequency) / PPMI / PLMI
> 
> Each of these is a very large file which is not easy for me to transfer (they are on a server in my previous university), so if you only need one of them, I'll send it, otherwise I think it's best that you use our code to reconstruct them.

Thank you! You're really a warm-hearted person!
At the current stage, I only need the <dependency-based + frequency> matrix.

**Comment by vered1986** [comment]
No problem :) 

You can download the pkl file from here: https://drive.google.com/open?id=1isaToLx-Ak4nhey8Hxx1LFcpdjj_Fce1. 

To get the co-occurrence matrix, call `vector_space = common.load_pkl_files("path/to/dep-based_freq)` (without the `pkl` extension) and access it with `vector_space.cooccurrence_matrix`.
